### ISSUE TITLE
Module parse failed for ESM Bundle

### ISSUE THREAD

**Issue by abhiburk** [bartdominiak/vue-snap#18]
After Installation I get this error.
I have configured it in local vue file

![image](https://user-images.githubusercontent.com/21901478/87846529-2f539580-c8ee-11ea-88ab-bdfd1dcb2430.png)

**Comment by bartdominiak** [comment]
Thanks for spotting that. I'll look over that.

**Comment by bartdominiak** [comment]
Sorry, but I cannot reproduce your issue. Can you please provide any code example?
I added also code examples [here](https://github.com/bartdominiak/vue-snap/tree/master/examples)

**Comment by bartdominiak** [comment]
Closed due inactivity.
