### ISSUE TITLE
TypeError in Safari, does not load

### ISSUE THREAD

**Issue by petedermott** [bartdominiak/vue-snap#47]
Just tried running this in Safari in my nuxt app and got the following error, this also doesn't work on the demo app you have running at [https://vue-snap.vercel.app/](https://vue-snap.vercel.app/)

`TypeError: undefined is not an object (evaulating 'options.left')`
![image](https://user-images.githubusercontent.com/7780261/98795914-b5966900-2402-11eb-8008-2c3a1b9310b0.png)

I looks like it _may_ be due to the seamless-scroll-polyfill but I'm pretty new to Vue so I'm not 100% sure.

This is with Safari 13.1 on MacOS Catalina and Safari on iOS 14.2

**Comment by klongmitre** [comment]
I'm running into this too. @bartdominiak any thoughts on how this can be remedied? Very much interested in using this component in a vue-2 app.

**Comment by bartdominiak** [comment]
Thanks for spotting this issue!
Already fixed and released in `vue-snap@0.6.3`
