### ISSUE TITLE
es.array.every.js dependancy seems to be missing with NPM installation

### ISSUE THREAD

**Issue by petedermott** [bartdominiak/vue-snap#49]
Not sure if this is a regression with the release of v0.6.3 or if it is just me but I get the following error after updating and doing an `npm install`

![image](https://user-images.githubusercontent.com/7780261/99991429-edab8d80-2dac-11eb-933d-6739bed0e9cc.png)

**Comment by bartdominiak** [comment]
Strange, it's looks like you don't have `core-js` - it should be downloaded OOTB. Try to remove `node_modules` and install it again. I also checked [example](https://github.com/bartdominiak/vue-snap/tree/master/examples/vue%402/nuxt) folder with `vue-snap@0.6.3` and it's working as expected - via npm and yarn.

**Comment by petedermott** [comment]
Yeap, my bad. Removed my apps node_modules and started afresh, everything looks fine.

Thanks for your hard work on this!
