### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by bartdominiak** [bartdominiak/vue-snap#9]
- Check current support for Scroll Snapping in IE11 +
- Add babel polyfills to webpack

**Comment by HIMISOCOOL** [comment]
https://caniuse.com/css-snappoints
See the notes section for IE11's restrictions

**Comment by bartdominiak** [comment]
@HIMISOCOOL thank you for pointing that out. According to Statcounter Global Stats, I decided to not support IE anymore.
